# Required metadata
sonar.projectKey=mycurl-repo-key
sonar.projectName=mycurl
sonar.projectVersion=1.0

# SonarCloud server URL
sonar.host.url=https://sonarcloud.io

# Your authentication token (This is used for CI/CD and can be kept in environment variables)
sonar.login=41e011f890874035c5ecaa3e8429d13cd0adc83c

# Path to the source code
sonar.sources=.

# Optional: Exclude test files if you don't want to analyze them
sonar.exclusions=**/*.test.*, **/test/**
